-- Runtime H2 projection of composite invariants that are present in design/schema.sql but are not
-- currently emitted as JPA @Table(uniqueConstraints = ...) by the aggregate entity generator.
-- The reliable-event runtime owns __event; these alterations preserve its published text-column schema
-- when Hibernate create-drop derives shorter varchar columns from the current entity annotations.
alter table __event alter column data text;
alter table __event alter column execution_context text;
alter table __event alter column retry_policy text;

alter table reconciliation_batch
    add constraint uk_reconciliation_batch_scope unique (channel_id, currency, reconciliation_date);

alter table reconciliation_run
    add constraint uk_reconciliation_run_statement unique (batch_id, statement_identity, statement_revision);

alter table merchant_settlement
    add constraint uk_merchant_settlement_effective_scope unique (effective_scope_identity);

alter table settlement_line
    add constraint uk_settlement_line_identity unique (merchant_settlement_id, line_identity);

alter table settlement_line
    add constraint uk_settlement_line_source unique (merchant_settlement_id, source_kind, source_fact_identity);

alter table settlement_line
    add constraint uk_settlement_line_effective_consumption unique (effective_consumption_identity);

alter table settlement_execution_attempt
    add constraint uk_settlement_execution_attempt_request unique (channel_id, request_identity);

alter table settlement_execution_attempt
    add constraint uk_settlement_execution_attempt_sequence unique (merchant_settlement_id, attempt_sequence);

alter table settlement_result_receipt
    add constraint uk_settlement_result_receipt unique (settlement_execution_attempt_id, notification_identity);


alter table payment
    add constraint uk_payment_merchant_order_success unique (merchant_order_success_identity);

alter table payment
    add constraint uk_payment_notification_intent unique (merchant_success_notification_intent_identity);

alter table payment_notification_receipt
    add constraint uk_payment_notification_receipt_payload unique (payment_attempt_id, notification_identity, payload_identity);

alter table payment_review_case
    add constraint uk_payment_review_case unique (payment_id, review_identity);

alter table payment_review_decision
    add constraint uk_payment_review_decision unique (payment_review_case_id, decision_identity);

-- 人类可读的表/字段备注与 design/schema.sql 保持同一套业务语义；机器 token 也一并保留。
comment on table payment is '支付主聚合：记录商户订单的金额、状态、成功事实、通知收敛、复核和退款预算';
comment on table payment_attempt is '支付尝试：Payment 聚合内一次渠道请求及其最终结果与通知证据 @Parent=payment;';
comment on table payment_notification_receipt is '支付通知回执：保存渠道回调的原始身份、校验结果和重复/矛盾处理证据 @Parent=payment_attempt;';
comment on table payment_review_case is '支付复核案件：保存迟到、未知或矛盾支付结果的人工复核上下文 @Parent=payment;';
comment on table payment_review_decision is '支付复核决定：保存授权操作人对复核案件作出的追加式裁决证据 @Parent=payment_review_case;';
comment on table refund is '退款主聚合：记录退款申请、退款预算占用、渠道结果和最终退款事实';
comment on table refund_attempt is '退款尝试：Refund 聚合内一次渠道退款请求及其等待、结果和通知证据 @Parent=refund;';
comment on table refund_notification_receipt is '退款通知回执：保存渠道退款回调的身份、金额、校验和冲突证据 @Parent=refund_attempt;';
comment on table merchant_channel_configuration is '商户渠道配置：保存商户在渠道、币种和支付方式维度上的路由与费用快照来源';
comment on table reconciliation_batch is '对账批次：以渠道、币种和业务日为范围维护对账周期、有效运行和结算阻断状态';
comment on table reconciliation_run is '对账运行：保存某一账单身份与修订版本的拉取、匹配和完成结果 @Parent=reconciliation_batch;';
comment on table reconciliation_item is '对账差异项：保存渠道事实与平台事实的双方快照、匹配依据和处置状态 @Parent=reconciliation_run;';
comment on table reconciliation_disposition is '对账差异处置：保存操作人对差异项的授权、结论、影响和证据 @Parent=reconciliation_item;';
comment on table reconciliation_confirmation_fact is '对账确认事实：保存经授权确认后的外部交易事实，不覆盖原始差异证据 @Parent=reconciliation_item;';
comment on table merchant_settlement is '商户结算单：冻结结算构成并汇总毛额、手续费、调整额、净额与执行生命周期';
comment on table settlement_line is '结算明细：保存一条被纳入结算的支付、退款或对账确认来源及其费用快照 @Parent=merchant_settlement;';
comment on table settlement_execution_attempt is '结算执行尝试：保存一次出款请求、等待窗口、结果和重试/冲突证据 @Parent=merchant_settlement;';
comment on table settlement_result_receipt is '结算结果回执：保存渠道出款回调的稳定身份、金额、结果和重复/矛盾证据 @Parent=settlement_execution_attempt;';
comment on column payment.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column payment.version is '并发更新版本号 @Managed=version;';
comment on column payment.merchant_id is '商户标识';
comment on column payment.merchant_order_number is '商户订单号';
comment on column payment.idempotency_key is '请求幂等键';
comment on column payment.amount is '本次业务金额';
comment on column payment.currency is '业务币种';
comment on column payment.payment_method is '支付方式';
comment on column payment.status is '当前业务状态枚举 @Type=PaymentStatus;';
comment on column payment.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column payment.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column payment.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column payment.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column payment.expires_at is '支付有效期截止时间';
comment on column payment.succeeded_at is '支付成功事实形成时间';
comment on column payment.closed_at is '支付关闭时间';
comment on column payment.close_reason is '支付关闭原因';
comment on column payment.channel_transaction_id is '渠道交易标识';
comment on column payment.success_fact_formed is '成功事实是否已形成';
comment on column payment.merchant_order_success_identity is '商户订单成功稳定身份';
comment on column payment.attempt_count is '支付尝试数量';
comment on column payment.notification_receive_count is '通知累计接收次数';
comment on column payment.rejected_notification_count is '通知累计拒绝次数';
comment on column payment.conflicting_notification_count is '通知累计矛盾次数';
comment on column payment.last_notification_identity is '最近通知身份';
comment on column payment.last_notification_received_at is '最近通知接收时间';
comment on column payment.last_rejection_summary is '最近一次拒绝摘要';
comment on column payment.last_conflict_summary is '最近一次矛盾摘要';
comment on column payment.merchant_success_notification_intent_count is '商户成功通知意图次数';
comment on column payment.merchant_success_notification_intent_identity is '商户成功通知意图身份';
comment on column payment.merchant_success_notification_intent_state is '商户成功通知意图状态 @Type=PaymentNotificationIntentState;';
comment on column payment.review_count is '复核案件数量';
comment on column payment.blocking_review_count is '阻断性复核数量';
comment on column payment.settlement_fee_fact_identity is '结算手续费事实身份';
comment on column payment.settlement_fee_basis_points is '结算手续费基点';
comment on column payment.settlement_fixed_fee_amount is '结算固定手续费金额';
comment on column payment.settlement_fee_rounding_mode is '结算手续费舍入模式';
comment on column payment.settlement_fee_currency_precision is '手续费币种精度快照';
comment on column payment.settlement_fee_calculation_amount is '手续费计算基数快照';
comment on column payment.settlement_fee_amount is '手续费金额快照';
comment on column payment.settlement_fee_formed_at is '手续费事实形成时间';
comment on column payment.settlement_blocked is '是否阻断进入结算';
comment on column payment.reserved_refund_amount is '已占用退款金额';
comment on column payment.successful_refund_amount is '已成功退款金额';
comment on column payment_attempt.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column payment_attempt.version is '并发更新版本号 @Managed=version;';
comment on column payment_attempt.payment_id is '关联支付标识 @ParentRef;';
comment on column payment_attempt.channel_id is '渠道标识';
comment on column payment_attempt.channel_configuration_id is '渠道配置标识';
comment on column payment_attempt.channel_configuration_snapshot is '发起时使用的渠道配置快照';
comment on column payment_attempt.request_identity is '执行请求幂等身份';
comment on column payment_attempt.status is '当前业务状态枚举 @Type=PaymentAttemptStatus;';
comment on column payment_attempt.initiated_at is '渠道请求发起时间';
comment on column payment_attempt.channel_transaction_id is '渠道交易标识';
comment on column payment_attempt.final_result is '最终结果枚举 @Type=PaymentAttemptFinalResult;';
comment on column payment_attempt.result_occurred_at is '渠道结果发生时间';
comment on column payment_attempt.notification_identity is '渠道通知幂等身份';
comment on column payment_attempt.notification_receive_count is '通知累计接收次数';
comment on column payment_attempt.notification_first_received_at is '首次收到通知时间';
comment on column payment_attempt.notification_last_received_at is '最近收到通知时间';
comment on column payment_attempt.verified_notification_count is '通知累计验证通过次数';
comment on column payment_attempt.rejected_notification_count is '通知累计拒绝次数';
comment on column payment_attempt.conflicting_notification_count is '通知累计矛盾次数';
comment on column payment_attempt.verdict_summary is '系统判定摘要';
comment on column payment_attempt.rejection_summary is '拒绝处理摘要';
comment on column payment_attempt.conflict_summary is '矛盾处理摘要';
comment on column payment_attempt.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column payment_attempt.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column payment_attempt.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column payment_attempt.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column payment_notification_receipt.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column payment_notification_receipt.version is '并发更新版本号 @Managed=version;';
comment on column payment_notification_receipt.payment_attempt_id is '关联支付尝试标识 @ParentRef;';
comment on column payment_notification_receipt.notification_identity is '渠道通知幂等身份';
comment on column payment_notification_receipt.payload_identity is '通知载荷指纹身份';
comment on column payment_notification_receipt.channel_id is '渠道标识';
comment on column payment_notification_receipt.channel_transaction_id is '渠道交易标识';
comment on column payment_notification_receipt.amount is '本次业务金额';
comment on column payment_notification_receipt.currency is '业务币种';
comment on column payment_notification_receipt.result is '渠道原始结果';
comment on column payment_notification_receipt.occurred_at is '外部事实发生时间';
comment on column payment_notification_receipt.first_received_at is '首次收到通知时间';
comment on column payment_notification_receipt.last_received_at is '最近收到通知时间';
comment on column payment_notification_receipt.receive_count is '同一通知累计接收次数';
comment on column payment_notification_receipt.verified is '通知是否验证通过';
comment on column payment_notification_receipt.accepted is '通知是否被业务接受';
comment on column payment_notification_receipt.decision is '系统对通知的处理决策 @Type=ChannelResultDisposition;';
comment on column payment_notification_receipt.verdict_summary is '系统判定摘要';
comment on column payment_notification_receipt.rejection_summary is '拒绝处理摘要';
comment on column payment_notification_receipt.conflict_summary is '矛盾处理摘要';
comment on column payment_notification_receipt.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column payment_notification_receipt.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column payment_notification_receipt.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column payment_notification_receipt.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column payment_review_case.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column payment_review_case.version is '并发更新版本号 @Managed=version;';
comment on column payment_review_case.payment_id is '关联支付标识 @ParentRef;';
comment on column payment_review_case.review_identity is '复核案件身份';
comment on column payment_review_case.type is '用于记录类型 @Type=PaymentReviewType;';
comment on column payment_review_case.status is '当前业务状态枚举 @Type=PaymentReviewStatus;';
comment on column payment_review_case.opened_at is '复核案件开立时间';
comment on column payment_review_case.triggering_payment_status is '触发复核时的支付状态 @Type=PaymentStatus;';
comment on column payment_review_case.triggering_attempt_identities is '触发复核的尝试身份集合';
comment on column payment_review_case.triggering_receipt_identities is '触发复核的通知身份集合';
comment on column payment_review_case.summary is '复核案件业务摘要';
comment on column payment_review_case.settlement_impact is '对结算资格的影响枚举 @Type=PaymentReviewSettlementImpact;';
comment on column payment_review_case.resolved_at is '复核案件解决时间';
comment on column payment_review_case.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column payment_review_case.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column payment_review_case.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column payment_review_case.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column payment_review_decision.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column payment_review_decision.version is '并发更新版本号 @Managed=version;';
comment on column payment_review_decision.payment_review_case_id is '关联支付复核案件标识 @ParentRef;';
comment on column payment_review_decision.decision_identity is '用于记录决策稳定身份';
comment on column payment_review_decision.decision is '系统对通知的处理决策 @Type=PaymentReviewDecisionType;';
comment on column payment_review_decision.operator_identity is '操作人身份';
comment on column payment_review_decision.operator_role is '操作人角色';
comment on column payment_review_decision.authorization_outcome is '授权校验结果';
comment on column payment_review_decision.reason is '业务原因说明';
comment on column payment_review_decision.evidence is '业务证据文本';
comment on column payment_review_decision.decided_at is '裁决时间';
comment on column payment_review_decision.eligibility_impact is '对后续资格的影响枚举 @Type=PaymentReviewEligibilityImpact;';
comment on column payment_review_decision.remediation_reference is '补救动作引用';
comment on column payment_review_decision.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column payment_review_decision.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column payment_review_decision.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column payment_review_decision.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column refund.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column refund.version is '并发更新版本号 @Managed=version;';
comment on column refund.payment_id is '关联支付标识 @RefAggregate=Payment;';
comment on column refund.merchant_id is '商户标识';
comment on column refund.merchant_refund_number is '商户退款单号';
comment on column refund.amount is '本次业务金额';
comment on column refund.currency is '业务币种';
comment on column refund.payment_method is '支付方式';
comment on column refund.status is '当前业务状态枚举 @Type=RefundStatus;';
comment on column refund.requested_at is '退款申请时间';
comment on column refund.refund_deadline_at is '退款期限截止时间';
comment on column refund.channel_accepted_at is '渠道受理时间';
comment on column refund.finalized_at is '退款最终完成时间';
comment on column refund.review_required_at is '进入退款结果复核时间';
comment on column refund.channel_id is '渠道标识';
comment on column refund.channel_configuration_id is '渠道配置标识';
comment on column refund.channel_configuration_snapshot is '发起时使用的渠道配置快照';
comment on column refund.request_identity is '执行请求幂等身份';
comment on column refund.channel_refund_id is '渠道退款标识';
comment on column refund.reservation_active is '退款预算占用是否有效';
comment on column refund.reservation_released is '退款预算占用是否已释放';
comment on column refund.reservation_converted_to_success is '退款预算是否已转换为成功退款事实';
comment on column refund.success_fact_formed is '成功事实是否已形成';
comment on column refund.notification_receive_count is '通知累计接收次数';
comment on column refund.rejected_notification_count is '通知累计拒绝次数';
comment on column refund.conflicting_notification_count is '通知累计矛盾次数';
comment on column refund.last_notification_identity is '最近通知身份';
comment on column refund.last_notification_received_at is '最近通知接收时间';
comment on column refund.last_rejection_summary is '最近一次拒绝摘要';
comment on column refund.last_conflict_summary is '最近一次矛盾摘要';
comment on column refund.settlement_blocked is '是否阻断进入结算';
comment on column refund.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column refund.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column refund.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column refund.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column refund_attempt.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column refund_attempt.version is '并发更新版本号 @Managed=version;';
comment on column refund_attempt.refund_id is '关联退款标识 @ParentRef;';
comment on column refund_attempt.channel_id is '渠道标识';
comment on column refund_attempt.channel_configuration_id is '渠道配置标识';
comment on column refund_attempt.channel_configuration_snapshot is '发起时使用的渠道配置快照';
comment on column refund_attempt.request_identity is '执行请求幂等身份';
comment on column refund_attempt.status is '当前业务状态枚举 @Type=RefundAttemptStatus;';
comment on column refund_attempt.initiated_at is '渠道请求发起时间';
comment on column refund_attempt.accepted_at is '渠道受理时间';
comment on column refund_attempt.review_after_at is '进入结果复核的时间';
comment on column refund_attempt.channel_refund_id is '渠道退款标识';
comment on column refund_attempt.final_result is '最终结果枚举 @Type=RefundAttemptFinalResult;';
comment on column refund_attempt.result_occurred_at is '渠道结果发生时间';
comment on column refund_attempt.notification_receive_count is '通知累计接收次数';
comment on column refund_attempt.notification_first_received_at is '首次收到通知时间';
comment on column refund_attempt.notification_last_received_at is '最近收到通知时间';
comment on column refund_attempt.verified_notification_count is '通知累计验证通过次数';
comment on column refund_attempt.rejected_notification_count is '通知累计拒绝次数';
comment on column refund_attempt.conflicting_notification_count is '通知累计矛盾次数';
comment on column refund_attempt.verdict_summary is '系统判定摘要';
comment on column refund_attempt.rejection_summary is '拒绝处理摘要';
comment on column refund_attempt.conflict_summary is '矛盾处理摘要';
comment on column refund_attempt.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column refund_attempt.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column refund_attempt.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column refund_attempt.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column refund_notification_receipt.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column refund_notification_receipt.version is '并发更新版本号 @Managed=version;';
comment on column refund_notification_receipt.refund_attempt_id is '关联退款尝试标识 @ParentRef;';
comment on column refund_notification_receipt.notification_identity is '渠道通知幂等身份';
comment on column refund_notification_receipt.channel_id is '渠道标识';
comment on column refund_notification_receipt.channel_refund_id is '渠道退款标识';
comment on column refund_notification_receipt.amount is '本次业务金额';
comment on column refund_notification_receipt.currency is '业务币种';
comment on column refund_notification_receipt.result is '渠道原始结果';
comment on column refund_notification_receipt.occurred_at is '外部事实发生时间';
comment on column refund_notification_receipt.first_received_at is '首次收到通知时间';
comment on column refund_notification_receipt.last_received_at is '最近收到通知时间';
comment on column refund_notification_receipt.receive_count is '同一通知累计接收次数';
comment on column refund_notification_receipt.verified is '通知是否验证通过';
comment on column refund_notification_receipt.accepted is '通知是否被业务接受';
comment on column refund_notification_receipt.decision is '系统对通知的处理决策 @Type=RefundResultDisposition;';
comment on column refund_notification_receipt.verdict_summary is '系统判定摘要';
comment on column refund_notification_receipt.rejection_summary is '拒绝处理摘要';
comment on column refund_notification_receipt.conflict_summary is '矛盾处理摘要';
comment on column refund_notification_receipt.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column refund_notification_receipt.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column refund_notification_receipt.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column refund_notification_receipt.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column merchant_channel_configuration.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column merchant_channel_configuration.version is '并发更新版本号 @Managed=version;';
comment on column merchant_channel_configuration.merchant_id is '商户标识';
comment on column merchant_channel_configuration.channel_id is '渠道标识';
comment on column merchant_channel_configuration.currency is '业务币种';
comment on column merchant_channel_configuration.payment_method is '支付方式';
comment on column merchant_channel_configuration.minimum_amount is '渠道可受理最小金额';
comment on column merchant_channel_configuration.maximum_amount is '渠道可受理最大金额';
comment on column merchant_channel_configuration.status is '当前业务状态枚举 @Type=MerchantChannelConfigurationStatus;';
comment on column merchant_channel_configuration.routing_priority is '路由优先级';
comment on column merchant_channel_configuration.channel_rule_summary is '渠道路由规则摘要';
comment on column merchant_channel_configuration.refund_window_days is '退款窗口天数';
comment on column merchant_channel_configuration.refund_result_review_after_minutes is '退款结果复核等待分钟数';
comment on column merchant_channel_configuration.settlement_fee_basis_points is '结算手续费基点';
comment on column merchant_channel_configuration.settlement_fixed_fee_amount is '结算固定手续费金额';
comment on column merchant_channel_configuration.settlement_fee_rounding_mode is '结算手续费舍入模式';
comment on column merchant_channel_configuration.settlement_result_review_after_minutes is '结算结果复核等待分钟数';
comment on column merchant_channel_configuration.activated_at is '配置生效时间';
comment on column merchant_channel_configuration.retired_at is '配置退役时间';
comment on column merchant_channel_configuration.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column merchant_channel_configuration.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column merchant_channel_configuration.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column merchant_channel_configuration.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column reconciliation_batch.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column reconciliation_batch.version is '并发更新版本号 @Managed=version;';
comment on column reconciliation_batch.channel_id is '渠道标识';
comment on column reconciliation_batch.currency is '业务币种';
comment on column reconciliation_batch.reconciliation_date is '对账业务日期';
comment on column reconciliation_batch.business_timezone is '业务日计算时区';
comment on column reconciliation_batch.status is '当前业务状态枚举 @Type=ReconciliationBatchStatus;';
comment on column reconciliation_batch.current_effective_run_id is '当前生效对账运行标识';
comment on column reconciliation_batch.statement_wait_deadline_at is '等待账单截止时间';
comment on column reconciliation_batch.matched_count is '匹配数量';
comment on column reconciliation_batch.difference_count is '差异数量';
comment on column reconciliation_batch.unresolved_difference_count is '未解决差异数量';
comment on column reconciliation_batch.settlement_blocked is '是否阻断进入结算';
comment on column reconciliation_batch.blocking_reason is '阻断完成的原因';
comment on column reconciliation_batch.completed_at is '完成时间';
comment on column reconciliation_batch.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column reconciliation_batch.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column reconciliation_batch.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column reconciliation_batch.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column reconciliation_run.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column reconciliation_run.version is '并发更新版本号 @Managed=version;';
comment on column reconciliation_run.batch_id is '所属对账批次标识 @ParentRef;';
comment on column reconciliation_run.statement_identity is '账单稳定身份';
comment on column reconciliation_run.statement_revision is '账单修订版本';
comment on column reconciliation_run.statement_completeness is '账单完整性枚举 @Type=StatementCompleteness;';
comment on column reconciliation_run.status is '当前业务状态枚举 @Type=ReconciliationRunStatus;';
comment on column reconciliation_run.fetched_at is '账单拉取时间';
comment on column reconciliation_run.started_at is '运行开始时间';
comment on column reconciliation_run.completed_at is '完成时间';
comment on column reconciliation_run.channel_record_count is '渠道记录数量';
comment on column reconciliation_run.platform_fact_count is '平台事实数量';
comment on column reconciliation_run.matched_count is '匹配数量';
comment on column reconciliation_run.difference_count is '差异数量';
comment on column reconciliation_run.unresolved_difference_count is '未解决差异数量';
comment on column reconciliation_run.failure_summary is '运行失败摘要';
comment on column reconciliation_run.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column reconciliation_run.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column reconciliation_run.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column reconciliation_run.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column reconciliation_item.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column reconciliation_item.version is '并发更新版本号 @Managed=version;';
comment on column reconciliation_item.reconciliation_run_id is '所属对账运行标识 @ParentRef;';
comment on column reconciliation_item.difference_identity is '差异稳定身份';
comment on column reconciliation_item.transaction_kind is '交易类型枚举 @Type=ReconciliationTransactionKind;';
comment on column reconciliation_item.difference_type is '差异类型枚举 @Type=ReconciliationDifferenceType;';
comment on column reconciliation_item.channel_record_identity is '渠道记录身份';
comment on column reconciliation_item.channel_transaction_identity is '渠道交易身份';
comment on column reconciliation_item.channel_amount is '渠道侧交易金额';
comment on column reconciliation_item.channel_currency is '渠道侧币种';
comment on column reconciliation_item.channel_raw_status is '渠道原始状态';
comment on column reconciliation_item.channel_occurred_at is '渠道事实发生时间';
comment on column reconciliation_item.channel_received_at is '渠道事实接收时间';
comment on column reconciliation_item.platform_fact_identity is '平台事实身份';
comment on column reconciliation_item.payment_id is '关联支付标识';
comment on column reconciliation_item.payment_attempt_id is '关联支付尝试标识';
comment on column reconciliation_item.refund_id is '关联退款标识';
comment on column reconciliation_item.refund_attempt_id is '关联退款尝试标识';
comment on column reconciliation_item.platform_transaction_identity is '平台交易身份';
comment on column reconciliation_item.platform_amount is '平台事实金额';
comment on column reconciliation_item.platform_currency is '平台事实币种';
comment on column reconciliation_item.platform_raw_status is '平台原始状态';
comment on column reconciliation_item.platform_occurred_at is '平台事实发生时间';
comment on column reconciliation_item.platform_recorded_at is '平台事实记录时间';
comment on column reconciliation_item.payment_review_identity_snapshot is '支付复核身份快照';
comment on column reconciliation_item.payment_review_summary is '支付复核摘要';
comment on column reconciliation_item.matching_basis is '匹配依据说明';
comment on column reconciliation_item.auxiliary_match_approved is '是否允许辅助匹配';
comment on column reconciliation_item.resolved is '差异是否已解决';
comment on column reconciliation_item.settlement_blocked is '是否阻断进入结算';
comment on column reconciliation_item.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column reconciliation_item.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column reconciliation_item.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column reconciliation_item.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column reconciliation_disposition.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column reconciliation_disposition.version is '并发更新版本号 @Managed=version;';
comment on column reconciliation_disposition.reconciliation_item_id is '所属对账差异项标识 @ParentRef;';
comment on column reconciliation_disposition.operator_identity is '操作人身份';
comment on column reconciliation_disposition.operator_role is '操作人角色';
comment on column reconciliation_disposition.authorization_result is '授权校验结果枚举 @Type=DispositionAuthorization;';
comment on column reconciliation_disposition.status is '当前业务状态枚举 @Type=ReconciliationDispositionStatus;';
comment on column reconciliation_disposition.conclusion is '处置结论 @Type=ReconciliationDispositionConclusion;';
comment on column reconciliation_disposition.settlement_impact is '对结算资格的影响枚举 @Type=SettlementImpact;';
comment on column reconciliation_disposition.evidence is '业务证据文本';
comment on column reconciliation_disposition.follow_up is '后续处理说明';
comment on column reconciliation_disposition.disposed_at is '差异处置时间';
comment on column reconciliation_disposition.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column reconciliation_disposition.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column reconciliation_disposition.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column reconciliation_disposition.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column reconciliation_confirmation_fact.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column reconciliation_confirmation_fact.version is '并发更新版本号 @Managed=version;';
comment on column reconciliation_confirmation_fact.reconciliation_item_id is '所属对账差异项标识 @ParentRef;';
comment on column reconciliation_confirmation_fact.source_difference_identity is '来源差异身份';
comment on column reconciliation_confirmation_fact.merchant_id is '商户标识';
comment on column reconciliation_confirmation_fact.channel_id is '渠道标识';
comment on column reconciliation_confirmation_fact.operator_identity is '操作人身份';
comment on column reconciliation_confirmation_fact.confirmation_reason is '确认原因';
comment on column reconciliation_confirmation_fact.evidence is '业务证据文本';
comment on column reconciliation_confirmation_fact.transaction_kind is '交易类型枚举 @Type=ReconciliationTransactionKind;';
comment on column reconciliation_confirmation_fact.amount is '本次业务金额';
comment on column reconciliation_confirmation_fact.currency is '业务币种';
comment on column reconciliation_confirmation_fact.external_transaction_identity is '外部交易身份';
comment on column reconciliation_confirmation_fact.payment_id is '关联支付标识';
comment on column reconciliation_confirmation_fact.refund_id is '关联退款标识';
comment on column reconciliation_confirmation_fact.confirmed_at is '确认时间';
comment on column reconciliation_confirmation_fact.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column reconciliation_confirmation_fact.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column reconciliation_confirmation_fact.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column reconciliation_confirmation_fact.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column merchant_settlement.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column merchant_settlement.version is '并发更新版本号 @Managed=version;';
comment on column merchant_settlement.merchant_id is '商户标识';
comment on column merchant_settlement.channel_id is '渠道标识';
comment on column merchant_settlement.currency is '业务币种';
comment on column merchant_settlement.period_type is '结算周期类型';
comment on column merchant_settlement.period_start is '结算周期开始时间';
comment on column merchant_settlement.period_end is '结算周期结束时间';
comment on column merchant_settlement.business_timezone is '业务日计算时区';
comment on column merchant_settlement.scope_identity is '结算范围身份';
comment on column merchant_settlement.effective_scope_identity is '当前生效范围身份';
comment on column merchant_settlement.status is '当前业务状态枚举 @Type=MerchantSettlementStatus;';
comment on column merchant_settlement.eligible_count is '纳入结算的交易数量';
comment on column merchant_settlement.excluded_count is '排除交易数量';
comment on column merchant_settlement.blocker_summary is '结算阻断摘要';
comment on column merchant_settlement.payment_gross_amount is '支付毛额';
comment on column merchant_settlement.refund_gross_amount is '退款毛额';
comment on column merchant_settlement.fee_total_amount is '手续费合计';
comment on column merchant_settlement.adjustment_total_amount is '调整金额合计';
comment on column merchant_settlement.net_amount is '结算净额';
comment on column merchant_settlement.composition_frozen is '结算构成是否冻结';
comment on column merchant_settlement.execution_group_identity is '执行批次身份';
comment on column merchant_settlement.predecessor_settlement_id is '前序结算单标识';
comment on column merchant_settlement.replacement_settlement_id is '替代结算单标识';
comment on column merchant_settlement.confirmed_by is '确认操作人';
comment on column merchant_settlement.confirmed_at is '确认时间';
comment on column merchant_settlement.voided_by is '作废操作人';
comment on column merchant_settlement.void_reason is '作废原因';
comment on column merchant_settlement.voided_at is '作废时间';
comment on column merchant_settlement.settled_fact_formed is '结算完成事实是否已形成';
comment on column merchant_settlement.external_settlement_identity is '外部结算身份';
comment on column merchant_settlement.completed_at is '完成时间';
comment on column merchant_settlement.last_rejection_summary is '最近一次拒绝摘要';
comment on column merchant_settlement.last_conflict_summary is '最近一次矛盾摘要';
comment on column merchant_settlement.last_review_summary is '最近一次复核摘要';
comment on column merchant_settlement.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column merchant_settlement.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column merchant_settlement.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column merchant_settlement.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column settlement_line.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column settlement_line.version is '并发更新版本号 @Managed=version;';
comment on column settlement_line.merchant_settlement_id is '所属商户结算单标识 @ParentRef;';
comment on column settlement_line.line_identity is '结算明细稳定身份';
comment on column settlement_line.source_kind is '结算来源类型枚举 @Type=SettlementLineSourceKind;';
comment on column settlement_line.transaction_kind is '交易类型枚举 @Type=com.only4.cap4k.reference.payment.domain.aggregates.reconciliation_batch.enums.ReconciliationTransactionKind;';
comment on column settlement_line.source_fact_identity is '结算来源事实身份';
comment on column settlement_line.effective_consumption_identity is '来源事实消费身份';
comment on column settlement_line.fee_fact_identity is '手续费事实身份';
comment on column settlement_line.payment_id is '关联支付标识 @RefAggregate=Payment;';
comment on column settlement_line.payment_attempt_id is '关联支付尝试标识';
comment on column settlement_line.refund_id is '关联退款标识 @RefAggregate=Refund;';
comment on column settlement_line.refund_attempt_id is '关联退款尝试标识';
comment on column settlement_line.reconciliation_batch_id is '关联对账批次标识 @RefAggregate=ReconciliationBatch;';
comment on column settlement_line.reconciliation_run_id is '所属对账运行标识';
comment on column settlement_line.reconciliation_item_id is '所属对账差异项标识';
comment on column settlement_line.reconciliation_confirmation_fact_id is '关联对账确认事实标识';
comment on column settlement_line.external_transaction_identity is '外部交易身份';
comment on column settlement_line.gross_amount is '结算明细毛额';
comment on column settlement_line.fee_amount is '结算明细手续费';
comment on column settlement_line.signed_net_amount is '带符号结算净额';
comment on column settlement_line.currency is '业务币种';
comment on column settlement_line.occurred_at is '外部事实发生时间';
comment on column settlement_line.recorded_at is '记录时间';
comment on column settlement_line.fee_basis_points is '手续费基点';
comment on column settlement_line.fee_fixed_amount is '固定手续费金额';
comment on column settlement_line.fee_rounding_mode is '手续费舍入模式';
comment on column settlement_line.fee_currency_precision is '手续费币种精度';
comment on column settlement_line.fee_calculation_amount is '手续费计算金额';
comment on column settlement_line.eligibility_basis is '纳入结算的资格依据';
comment on column settlement_line.confirmation_reason is '确认原因';
comment on column settlement_line.confirmation_evidence is '确认证据';
comment on column settlement_line.adjustment_source_identity is '调整来源身份';
comment on column settlement_line.adjustment_evidence is '调整证据';
comment on column settlement_line.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column settlement_line.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column settlement_line.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column settlement_line.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column settlement_execution_attempt.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column settlement_execution_attempt.version is '并发更新版本号 @Managed=version;';
comment on column settlement_execution_attempt.merchant_settlement_id is '所属商户结算单标识 @ParentRef;';
comment on column settlement_execution_attempt.attempt_sequence is '结算执行尝试序号';
comment on column settlement_execution_attempt.execution_group_identity is '执行批次身份';
comment on column settlement_execution_attempt.request_identity is '执行请求幂等身份';
comment on column settlement_execution_attempt.channel_id is '渠道标识';
comment on column settlement_execution_attempt.status is '当前业务状态枚举 @Type=SettlementExecutionAttemptStatus;';
comment on column settlement_execution_attempt.initiated_at is '渠道请求发起时间';
comment on column settlement_execution_attempt.accepted_at is '渠道受理时间';
comment on column settlement_execution_attempt.review_after_minutes_snapshot is '结果复核等待分钟数快照';
comment on column settlement_execution_attempt.review_after_at is '进入结果复核的时间';
comment on column settlement_execution_attempt.amount is '本次业务金额';
comment on column settlement_execution_attempt.currency is '业务币种';
comment on column settlement_execution_attempt.external_settlement_identity is '外部结算身份';
comment on column settlement_execution_attempt.final_result is '最终结果枚举 @Type=SettlementExecutionFinalResult;';
comment on column settlement_execution_attempt.result_occurred_at is '渠道结果发生时间';
comment on column settlement_execution_attempt.notification_receive_count is '通知累计接收次数';
comment on column settlement_execution_attempt.notification_first_received_at is '首次收到通知时间';
comment on column settlement_execution_attempt.notification_last_received_at is '最近收到通知时间';
comment on column settlement_execution_attempt.verified_notification_count is '通知累计验证通过次数';
comment on column settlement_execution_attempt.rejected_notification_count is '通知累计拒绝次数';
comment on column settlement_execution_attempt.conflicting_notification_count is '通知累计矛盾次数';
comment on column settlement_execution_attempt.verdict_summary is '系统判定摘要';
comment on column settlement_execution_attempt.rejection_summary is '拒绝处理摘要';
comment on column settlement_execution_attempt.conflict_summary is '矛盾处理摘要';
comment on column settlement_execution_attempt.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column settlement_execution_attempt.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column settlement_execution_attempt.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column settlement_execution_attempt.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
comment on column settlement_result_receipt.id is '记录唯一标识 @Managed=identifier.uuid7;';
comment on column settlement_result_receipt.version is '并发更新版本号 @Managed=version;';
comment on column settlement_result_receipt.settlement_execution_attempt_id is '关联结算执行尝试标识 @ParentRef;';
comment on column settlement_result_receipt.notification_identity is '渠道通知幂等身份';
comment on column settlement_result_receipt.payload_fingerprint is '通知载荷指纹';
comment on column settlement_result_receipt.channel_id is '渠道标识';
comment on column settlement_result_receipt.execution_group_identity is '执行批次身份';
comment on column settlement_result_receipt.request_identity is '执行请求幂等身份';
comment on column settlement_result_receipt.external_settlement_identity is '外部结算身份';
comment on column settlement_result_receipt.amount is '本次业务金额';
comment on column settlement_result_receipt.currency is '业务币种';
comment on column settlement_result_receipt.result is '渠道原始结果';
comment on column settlement_result_receipt.result_code is '渠道原始结果码';
comment on column settlement_result_receipt.occurred_at is '外部事实发生时间';
comment on column settlement_result_receipt.first_received_at is '首次收到通知时间';
comment on column settlement_result_receipt.last_received_at is '最近收到通知时间';
comment on column settlement_result_receipt.receive_count is '同一通知累计接收次数';
comment on column settlement_result_receipt.verified is '通知是否验证通过';
comment on column settlement_result_receipt.accepted is '通知是否被业务接受';
comment on column settlement_result_receipt.decision is '系统对通知的处理决策 @Type=SettlementResultDisposition;';
comment on column settlement_result_receipt.verdict_summary is '系统判定摘要';
comment on column settlement_result_receipt.rejection_summary is '拒绝处理摘要';
comment on column settlement_result_receipt.conflict_summary is '矛盾处理摘要';
comment on column settlement_result_receipt.created_at is '记录创建时间 @Managed=enrichment.audit-time.created-at;';
comment on column settlement_result_receipt.created_by is '记录创建者 @Managed=enrichment.audit-actor.created-by;';
comment on column settlement_result_receipt.updated_at is '记录最后更新时间 @Managed=enrichment.audit-time.updated-at;';
comment on column settlement_result_receipt.updated_by is '记录最后更新者 @Managed=enrichment.audit-actor.updated-by;';
