drop table if exists settlement_result_receipt;
drop table if exists settlement_execution_attempt;
drop table if exists settlement_line;
drop table if exists merchant_settlement;
drop table if exists reconciliation_confirmation_fact;
drop table if exists reconciliation_disposition;
drop table if exists reconciliation_item;
drop table if exists reconciliation_run;
drop table if exists reconciliation_batch;
drop table if exists refund_notification_receipt;
drop table if exists refund_attempt;
drop table if exists refund;
drop table if exists payment_notification_receipt;
drop table if exists payment_attempt;
drop table if exists merchant_channel_configuration;
drop table if exists payment;

create table payment (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    merchant_id varchar(64) not null,
    merchant_order_number varchar(128) not null,
    idempotency_key varchar(128) not null,
    amount decimal(19, 4) not null,
    currency varchar(3) not null,
    payment_method varchar(64) not null,
    status integer not null comment '@Type=PaymentStatus;',
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    expires_at timestamp with time zone not null,
    succeeded_at timestamp with time zone,
    channel_transaction_id varchar(128),
    success_fact_formed boolean not null default false,
    attempt_count integer not null default 0,
    notification_receive_count integer not null default 0,
    rejected_notification_count integer not null default 0,
    conflicting_notification_count integer not null default 0,
    last_notification_identity varchar(128),
    last_notification_received_at timestamp with time zone,
    last_rejection_summary varchar(1024),
    last_conflict_summary varchar(1024),
    merchant_success_notification_intent_count integer not null default 0,
    settlement_fee_fact_identity varchar(128),
    settlement_fee_basis_points integer,
    settlement_fixed_fee_amount decimal(19, 4),
    settlement_fee_rounding_mode varchar(32),
    settlement_fee_currency_precision integer,
    settlement_fee_calculation_amount decimal(19, 4),
    settlement_fee_amount decimal(19, 4),
    settlement_fee_formed_at timestamp with time zone,
    settlement_blocked boolean not null default false,
    reserved_refund_amount decimal(19, 4) not null,
    successful_refund_amount decimal(19, 4) not null,
    constraint uk_payment_merchant_idempotency unique (merchant_id, idempotency_key)
);

create table payment_attempt (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    payment_id varchar(36) not null comment '@ParentRef;',
    channel_id varchar(64) not null,
    channel_configuration_id varchar(36) not null,
    channel_configuration_snapshot varchar(2048) not null,
    request_identity varchar(128) not null,
    status integer not null comment '@Type=PaymentAttemptStatus;',
    initiated_at timestamp with time zone not null,
    channel_transaction_id varchar(128),
    final_result integer comment '@Type=PaymentAttemptFinalResult;',
    result_occurred_at timestamp with time zone,
    notification_identity varchar(128),
    notification_receive_count integer not null default 0,
    notification_first_received_at timestamp with time zone,
    notification_last_received_at timestamp with time zone,
    verified_notification_count integer not null default 0,
    rejected_notification_count integer not null default 0,
    conflicting_notification_count integer not null default 0,
    verdict_summary varchar(1024),
    rejection_summary varchar(1024),
    conflict_summary varchar(1024),
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_payment_attempt_request unique (channel_id, request_identity)
);
comment on table payment_attempt is '@Parent=payment;';

create table payment_notification_receipt (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    payment_attempt_id varchar(36) not null comment '@ParentRef;',
    notification_identity varchar(128) not null,
    channel_id varchar(64) not null,
    channel_transaction_id varchar(128) not null,
    amount decimal(19, 4) not null,
    currency varchar(3) not null,
    result varchar(32) not null,
    occurred_at timestamp with time zone not null,
    first_received_at timestamp with time zone not null,
    last_received_at timestamp with time zone not null,
    receive_count integer not null default 1,
    verified boolean not null default false,
    accepted boolean not null default false,
    decision integer not null comment '@Type=ChannelResultDisposition;',
    verdict_summary varchar(1024),
    rejection_summary varchar(1024),
    conflict_summary varchar(1024),
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_payment_notification_receipt unique (payment_attempt_id, notification_identity)
);
comment on table payment_notification_receipt is '@Parent=payment_attempt;';

create table refund (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    payment_id varchar(36) not null comment '@RefAggregate=Payment;',
    merchant_id varchar(64) not null,
    merchant_refund_number varchar(128) not null,
    amount decimal(19, 4) not null,
    currency varchar(3) not null,
    payment_method varchar(64) not null,
    status integer not null comment '@Type=RefundStatus;',
    requested_at timestamp with time zone not null,
    refund_deadline_at timestamp with time zone not null,
    channel_accepted_at timestamp with time zone,
    finalized_at timestamp with time zone,
    review_required_at timestamp with time zone,
    channel_id varchar(64) not null,
    channel_configuration_id varchar(36) not null,
    channel_configuration_snapshot varchar(2048) not null,
    request_identity varchar(128) not null,
    channel_refund_id varchar(128),
    reservation_active boolean not null default true,
    reservation_released boolean not null default false,
    reservation_converted_to_success boolean not null default false,
    success_fact_formed boolean not null default false,
    notification_receive_count integer not null default 0,
    rejected_notification_count integer not null default 0,
    conflicting_notification_count integer not null default 0,
    last_notification_identity varchar(128),
    last_notification_received_at timestamp with time zone,
    last_rejection_summary varchar(1024),
    last_conflict_summary varchar(1024),
    settlement_blocked boolean not null default false,
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_refund_merchant_number unique (merchant_id, merchant_refund_number)
);

create table refund_attempt (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    refund_id varchar(36) not null comment '@ParentRef;',
    channel_id varchar(64) not null,
    channel_configuration_id varchar(36) not null,
    channel_configuration_snapshot varchar(2048) not null,
    request_identity varchar(128) not null,
    status integer not null comment '@Type=RefundAttemptStatus;',
    initiated_at timestamp with time zone not null,
    accepted_at timestamp with time zone,
    review_after_at timestamp with time zone not null,
    channel_refund_id varchar(128),
    final_result integer comment '@Type=RefundAttemptFinalResult;',
    result_occurred_at timestamp with time zone,
    notification_receive_count integer not null default 0,
    notification_first_received_at timestamp with time zone,
    notification_last_received_at timestamp with time zone,
    verified_notification_count integer not null default 0,
    rejected_notification_count integer not null default 0,
    conflicting_notification_count integer not null default 0,
    verdict_summary varchar(1024),
    rejection_summary varchar(1024),
    conflict_summary varchar(1024),
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_refund_attempt_request unique (channel_id, request_identity)
);
comment on table refund_attempt is '@Parent=refund;';

create table refund_notification_receipt (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    refund_attempt_id varchar(36) not null comment '@ParentRef;',
    notification_identity varchar(128) not null,
    channel_id varchar(64) not null,
    channel_refund_id varchar(128) not null,
    amount decimal(19, 4) not null,
    currency varchar(3) not null,
    result varchar(32) not null,
    occurred_at timestamp with time zone not null,
    first_received_at timestamp with time zone not null,
    last_received_at timestamp with time zone not null,
    receive_count integer not null default 1,
    verified boolean not null default false,
    accepted boolean not null default false,
    decision integer not null comment '@Type=RefundResultDisposition;',
    verdict_summary varchar(1024),
    rejection_summary varchar(1024),
    conflict_summary varchar(1024),
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_refund_notification_receipt unique (refund_attempt_id, notification_identity)
);
comment on table refund_notification_receipt is '@Parent=refund_attempt;';

create table merchant_channel_configuration (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    merchant_id varchar(64) not null,
    channel_id varchar(64) not null,
    currency varchar(3) not null,
    payment_method varchar(64) not null,
    minimum_amount decimal(19, 4) not null,
    maximum_amount decimal(19, 4) not null,
    status integer not null comment '@Type=MerchantChannelConfigurationStatus;',
    routing_priority integer not null default 100,
    channel_rule_summary varchar(2048) not null,
    refund_window_days integer not null default 180,
    refund_result_review_after_minutes integer not null default 30,
    settlement_fee_basis_points integer not null default 200,
    settlement_fixed_fee_amount decimal(19, 4) not null,
    settlement_fee_rounding_mode varchar(32) not null default 'HALF_UP',
    settlement_result_review_after_minutes integer not null default 30,
    activated_at timestamp with time zone not null,
    retired_at timestamp with time zone,
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_merchant_channel_configuration unique (merchant_id, channel_id, currency, payment_method)
);

create table reconciliation_batch (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    channel_id varchar(64) not null,
    currency varchar(3) not null,
    reconciliation_date date not null,
    business_timezone varchar(64) not null,
    status integer not null comment '@Type=ReconciliationBatchStatus;',
    current_effective_run_id varchar(36),
    statement_wait_deadline_at timestamp with time zone not null,
    matched_count integer not null default 0,
    difference_count integer not null default 0,
    unresolved_difference_count integer not null default 0,
    settlement_blocked boolean not null default true,
    blocking_reason varchar(2048),
    completed_at timestamp with time zone,
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_reconciliation_batch_scope unique (channel_id, currency, reconciliation_date)
);

create table reconciliation_run (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    batch_id varchar(36) not null comment '@ParentRef;',
    statement_identity varchar(128) not null,
    statement_revision varchar(64) not null,
    statement_completeness integer not null comment '@Type=StatementCompleteness;',
    status integer not null comment '@Type=ReconciliationRunStatus;',
    fetched_at timestamp with time zone not null,
    started_at timestamp with time zone not null,
    completed_at timestamp with time zone,
    channel_record_count integer not null default 0,
    platform_fact_count integer not null default 0,
    matched_count integer not null default 0,
    difference_count integer not null default 0,
    unresolved_difference_count integer not null default 0,
    failure_summary varchar(2048),
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_reconciliation_run_statement unique (batch_id, statement_identity, statement_revision)
);
comment on table reconciliation_run is '@Parent=reconciliation_batch;';

create table reconciliation_item (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    reconciliation_run_id varchar(36) not null comment '@ParentRef;',
    difference_identity varchar(128) not null,
    transaction_kind integer not null comment '@Type=ReconciliationTransactionKind;',
    difference_type integer not null comment '@Type=ReconciliationDifferenceType;',
    channel_record_identity varchar(128),
    channel_transaction_identity varchar(128),
    channel_amount decimal(19, 4),
    channel_currency varchar(3),
    channel_raw_status varchar(64),
    channel_occurred_at timestamp with time zone,
    channel_received_at timestamp with time zone,
    platform_fact_identity varchar(128),
    payment_id varchar(36),
    payment_attempt_id varchar(36),
    refund_id varchar(36),
    refund_attempt_id varchar(36),
    platform_transaction_identity varchar(128),
    platform_amount decimal(19, 4),
    platform_currency varchar(3),
    platform_raw_status varchar(64),
    platform_occurred_at timestamp with time zone,
    platform_recorded_at timestamp with time zone,
    matching_basis varchar(2048) not null,
    auxiliary_match_approved boolean not null default false,
    resolved boolean not null default false,
    settlement_blocked boolean not null default true,
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_reconciliation_item_difference unique (reconciliation_run_id, difference_identity)
);
comment on table reconciliation_item is '@Parent=reconciliation_run;';

create table reconciliation_disposition (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    reconciliation_item_id varchar(36) not null comment '@ParentRef;',
    operator_identity varchar(128) not null,
    operator_role varchar(128) not null,
    authorization_result integer not null comment '@Type=DispositionAuthorization;',
    status integer not null comment '@Type=ReconciliationDispositionStatus;',
    conclusion integer comment '@Type=ReconciliationDispositionConclusion;',
    settlement_impact integer not null comment '@Type=SettlementImpact;',
    evidence varchar(4096) not null,
    follow_up varchar(2048),
    disposed_at timestamp with time zone not null,
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;'
);
comment on table reconciliation_disposition is '@Parent=reconciliation_item;';

create table reconciliation_confirmation_fact (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    reconciliation_item_id varchar(36) not null comment '@ParentRef;',
    source_difference_identity varchar(128) not null,
    merchant_id varchar(64) not null,
    channel_id varchar(64) not null,
    operator_identity varchar(128) not null,
    confirmation_reason varchar(2048) not null,
    evidence varchar(4096) not null,
    transaction_kind integer not null comment '@Type=ReconciliationTransactionKind;',
    amount decimal(19, 4) not null,
    currency varchar(3) not null,
    external_transaction_identity varchar(128) not null,
    payment_id varchar(36),
    refund_id varchar(36),
    confirmed_at timestamp with time zone not null,
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;'
);
comment on table reconciliation_confirmation_fact is '@Parent=reconciliation_item;';

create table merchant_settlement (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    merchant_id varchar(64) not null,
    channel_id varchar(64) not null,
    currency varchar(3) not null,
    period_type varchar(32) not null default 'DAILY',
    period_start timestamp with time zone not null,
    period_end timestamp with time zone not null,
    business_timezone varchar(64) not null,
    scope_identity varchar(512) not null,
    effective_scope_identity varchar(512),
    status integer not null comment '@Type=MerchantSettlementStatus;',
    eligible_count integer not null default 0,
    excluded_count integer not null default 0,
    blocker_summary varchar(4096),
    payment_gross_amount decimal(19, 4) not null,
    refund_gross_amount decimal(19, 4) not null,
    fee_total_amount decimal(19, 4) not null,
    adjustment_total_amount decimal(19, 4) not null,
    net_amount decimal(19, 4) not null,
    composition_frozen boolean not null default false,
    execution_group_identity varchar(128),
    predecessor_settlement_id varchar(36),
    replacement_settlement_id varchar(36),
    confirmed_by varchar(128),
    confirmed_at timestamp with time zone,
    voided_by varchar(128),
    void_reason varchar(2048),
    voided_at timestamp with time zone,
    settled_fact_formed boolean not null default false,
    external_settlement_identity varchar(128),
    completed_at timestamp with time zone,
    last_rejection_summary varchar(2048),
    last_conflict_summary varchar(2048),
    last_review_summary varchar(2048),
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_merchant_settlement_effective_scope unique (effective_scope_identity)
);

create table settlement_line (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    merchant_settlement_id varchar(36) not null comment '@ParentRef;',
    line_identity varchar(128) not null,
    source_kind integer not null comment '@Type=SettlementLineSourceKind;',
    transaction_kind integer not null comment '@Type=com.only4.cap4k.reference.payment.domain.aggregates.reconciliation_batch.enums.ReconciliationTransactionKind;',
    source_fact_identity varchar(128) not null,
    effective_consumption_identity varchar(512),
    fee_fact_identity varchar(128),
    payment_id varchar(36) comment '@RefAggregate=Payment;',
    payment_attempt_id varchar(36),
    refund_id varchar(36) comment '@RefAggregate=Refund;',
    refund_attempt_id varchar(36),
    reconciliation_batch_id varchar(36) comment '@RefAggregate=ReconciliationBatch;',
    reconciliation_run_id varchar(36),
    reconciliation_item_id varchar(36),
    reconciliation_confirmation_fact_id varchar(36),
    external_transaction_identity varchar(128) not null,
    gross_amount decimal(19, 4) not null,
    fee_amount decimal(19, 4) not null,
    signed_net_amount decimal(19, 4) not null,
    currency varchar(3) not null,
    occurred_at timestamp with time zone not null,
    recorded_at timestamp with time zone not null,
    fee_basis_points integer,
    fee_fixed_amount decimal(19, 4),
    fee_rounding_mode varchar(32),
    fee_currency_precision integer,
    fee_calculation_amount decimal(19, 4),
    eligibility_basis varchar(2048) not null,
    confirmation_reason varchar(2048),
    confirmation_evidence varchar(4096),
    adjustment_source_identity varchar(128),
    adjustment_evidence varchar(4096),
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_settlement_line_identity unique (merchant_settlement_id, line_identity),
    constraint uk_settlement_line_source unique (merchant_settlement_id, source_kind, source_fact_identity),
    constraint uk_settlement_line_effective_consumption unique (effective_consumption_identity)
);
comment on table settlement_line is '@Parent=merchant_settlement;';

create table settlement_execution_attempt (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    merchant_settlement_id varchar(36) not null comment '@ParentRef;',
    attempt_sequence integer not null,
    execution_group_identity varchar(128) not null,
    request_identity varchar(128) not null,
    channel_id varchar(64) not null,
    status integer not null comment '@Type=SettlementExecutionAttemptStatus;',
    initiated_at timestamp with time zone not null,
    accepted_at timestamp with time zone,
    review_after_minutes_snapshot integer not null,
    review_after_at timestamp with time zone not null,
    amount decimal(19, 4) not null,
    currency varchar(3) not null,
    external_settlement_identity varchar(128),
    final_result integer comment '@Type=SettlementExecutionFinalResult;',
    result_occurred_at timestamp with time zone,
    notification_receive_count integer not null default 0,
    notification_first_received_at timestamp with time zone,
    notification_last_received_at timestamp with time zone,
    verified_notification_count integer not null default 0,
    rejected_notification_count integer not null default 0,
    conflicting_notification_count integer not null default 0,
    verdict_summary varchar(2048),
    rejection_summary varchar(2048),
    conflict_summary varchar(2048),
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_settlement_execution_attempt_request unique (channel_id, request_identity),
    constraint uk_settlement_execution_attempt_sequence unique (merchant_settlement_id, attempt_sequence)
);
comment on table settlement_execution_attempt is '@Parent=merchant_settlement;';

create table settlement_result_receipt (
    id varchar(36) primary key comment '@Managed=identifier.uuid7;',
    version bigint not null default 0 comment '@Managed=version;',
    settlement_execution_attempt_id varchar(36) not null comment '@ParentRef;',
    notification_identity varchar(128) not null,
    payload_fingerprint varchar(128) not null,
    channel_id varchar(64) not null,
    execution_group_identity varchar(128) not null,
    request_identity varchar(128) not null,
    external_settlement_identity varchar(128) not null,
    amount decimal(19, 4) not null,
    currency varchar(3) not null,
    result varchar(32) not null,
    result_code varchar(128),
    occurred_at timestamp with time zone not null,
    first_received_at timestamp with time zone not null,
    last_received_at timestamp with time zone not null,
    receive_count integer not null default 1,
    verified boolean not null default false,
    accepted boolean not null default false,
    decision integer not null comment '@Type=SettlementResultDisposition;',
    verdict_summary varchar(2048),
    rejection_summary varchar(2048),
    conflict_summary varchar(2048),
    created_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.created-at;',
    created_by varchar(128) not null comment '@Managed=enrichment.audit-actor.created-by;',
    updated_at timestamp with time zone not null comment '@Managed=enrichment.audit-time.updated-at;',
    updated_by varchar(128) not null comment '@Managed=enrichment.audit-actor.updated-by;',
    constraint uk_settlement_result_receipt unique (settlement_execution_attempt_id, notification_identity)
);
comment on table settlement_result_receipt is '@Parent=settlement_execution_attempt;';
