flowchart TD
  N1["ActivateMerchantSettlementCmd.Request"]
  N2["PrepareMerchantSettlementCmd.Request"]
  N3["MerchantSettlementActivationRequestedDomainEvent"]
  N4["merchant-settlement.prepare [POST /api/merchant-settlements]"]
  N2 -->|CommandToDomainEvent| N3
  N3 -->|DomainEventToCommand| N1
  N4 -->|EndpointHttpBindingToCommand| N2

